name: build
on:
  branches:
    - main
  push:
    tags: v*
jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Login GitHub Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get Git Tag
        run: echo GIT_TAG=$(echo ${{ github.ref }} | sed -e "s#^refs/tags/v##g") >>$GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            "ghcr.io/${{ github.repository_owner }}/r53update:${{ env.GIT_TAG }}"
            "ghcr.io/${{ github.repository_owner }}/r53update:latest"

      - name: Push Docker image
        run: |
          docker push "ghcr.io/${{ github.repository_owner }}/r53update:${{ env.GIT_TAG }}"
          docker push "ghcr.io/${{ github.repository_owner }}/r53update:latest"
